"$schema" = "https://raw.githubusercontent.com/recaptimedev-labs/workers-config-schema/refs/heads/main/config-schema.json"
name = "r2-dirlist"
main = "src/index.ts"
compatibility_date = "2025-06-01"
account_id = "cf0bd808c6a294fd8c4d8f6d2cdeca05"

# disable both workers.dev and preview URLs since they only work on
# custom domains for R2 buckets
workers_dev = false
preview_urls = false

# Make sure this worker is routed proerly to the R2 buckets' custom domains.
routes = [
    { pattern = "cdn.andreijiroh.dev/*", zone_name = "andreijiroh.dev" },
    { pattern = "projects.cdn.andreijiroh.dev/*", zone_name = "andreijiroh.dev" },
    { pattern = "pub.r2.andreijiroh.dev/*", zone_name = "andreijiroh.dev" },
    { pattern = "projects.r2.andreijiroh.dev/*", zone_name = "andreijiroh.dev" }
]

# Bind an R2 Bucket. Use R2 to store arbitrarily large blobs of data, such as files.
# Docs: https://developers.cloudflare.com/r2/api/workers/workers-api-usage/
r2_buckets  = [
    { binding = "r2_pub", bucket_name = "pubfiles"},
    { binding = "r2_projectsStash", bucket_name = "projects"}
]

[observability]
# https://developers.cloudflare.com/workers/observability/logs/workers-logs/
enabled = true
head_sampling_rate = 1 # optional. default = 1.
