import { Env, SiteConfig } from './types';

export function getSiteConfig(env: Env, domain: string): SiteConfig | undefined {
  const pubfiles: SiteConfig = {
    name: "~ajhalili2006's public files stash",
    desp: {
      "/": "This is ~ajhalili2006's stash, now hosted on Cloudflare R2.",
      "/craiyon-hellscape": `A collection of AI-generated images from <a href="https://www.craiyon.com/">Craiyon (formerly DALL-E Mini)</a> that I found interesting or experimented with. Note that even though the images are generated by AI, I am taking responsibility on the copyright and licensing of these AI-generated images.`,
      "/multifandom-hellscapes": "My mutlifandom activities as usual. May include backups of AO3 fanfics and other fanworks from the fandoms I am in.",
      "/pfps": "Public archive of profile pictures from various social accounts I have used over the years.",
      "/screenshots": "Screenshots galore. (Expect possible leaks for upcoming projects and stuff, although I taken care on that.)",
      "/wallpapers": "Public archive of wallpapers I have used over the years.",
      "/wallpapers/stellapent-cier": "Wallpapers relating to Gildedguy Stories and Stellapent Cier, excluding patron-only content (they're stashed at my Google Photos library instead).",
    },
    bucket: env.r2_pub,
    legalInfo: `\
    Some parts of this stash may be licensed by respective authors and only used for personal and non-profit use only. If you have questions or would do you like to take down something off this public R2 bucket, please <a href="https://andreijiroh.dev/contact">contact me</a> first.`,
    decodeURI: true,
  }

  const projectsStash: SiteConfig = {
    name: "~ajhalili2006's projects stash",
    desp: {
      "/": "Public home for my non-code projects (i.e. Gen AI experiments, school projects, etc.)",
    },
    bucket: env.r2_projectsStash,
    legalInfo: `Unless stated otherwise, all projects are licensed under the <a href="https://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>. If you have questions or would do you like to take down something off this public R2 bucket, please <a href="https://andreijiroh.dev/contact">contact me</a> first.`,
  }

  const projects: SiteConfig = {
    name: "~ajhalili2006's projects stash",
    desp: {
      "/": "",
    },
    bucket: env.r2_projectsStash
  }
  
  const configs: {[domain: string]: SiteConfig} = {
    "cdn.andreijiroh.dev": pubfiles,
    "projects.cdn.andreijiroh.dev": projectsStash,
    "pub.r2.andreijiroh.dev": pubfiles,
    "projects.r2.andreijiroh.dev": projectsStash,
  };
  
  return configs[domain];
}